In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

In [ ]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

:

In [3]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [4]:
credits.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [5]:
# concatinate data by id
renamed_credits = credits.rename(columns={"movie_id": "id"})
renamed_credits = renamed_credits.drop(columns=["title"])

In [6]:
data = movies.merge(renamed_credits, on="id")
data.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [7]:
movies = data[['id','overview','genres','keywords','title','vote_average','release_date','cast','crew']].copy()
movies.head(2)

,id,overview,genres,keywords,title,vote_average,release_date,cast,crew
0,19995,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,7.2,2009-12-10,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,6.9,2007-05-19,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [8]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            4803 non-null   int64
 1   overview      4800 non-null   object
 2   genres        4803 non-null   object
 3   keywords      4803 non-null   object
 4   title         4803 non-null   object
 5   vote_average  4803 non-null   float64
 6   release_date  4802 non-null   object
 7   cast          4803 non-null   object
 8   crew          4803 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 337.8+ KB

In [9]:
movies['release_date'] = movies['release_date'].fillna('N/A')

In [10]:
movies.duplicated().sum()

0

In [11]:
import ast
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [12]:
movies.loc[:, 'genres'] = movies['genres'].apply(convert)
movies.loc[:,"keywords"] = movies["keywords"].apply(convert)

In [13]:
movies.head()

,id,overview,genres,keywords,title,vote_average,release_date,cast,crew
0,19995,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,7.2,2009-12-10,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,6.9,2007-05-19,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,6.3,2015-10-26,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,7.6,2012-07-16,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",John Carter,6.1,2012-03-07,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
#extract name from cast
def extract_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [15]:
movies.loc[:, "crew"] = movies["crew"].apply(extract_director)
movies.head(3)

,id,overview,genres,keywords,title,vote_average,release_date,cast,crew
0,19995,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,7.2,2009-12-10,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",[James Cameron]
1,285,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,6.9,2007-05-19,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",[Gore Verbinski]
2,206647,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,6.3,2015-10-26,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[Sam Mendes]

In [16]:
# extract 4 characters from cast
def extract_name(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 4:
            L.append(i['name'])
            counter += 1
        else:
            break
    return L

In [17]:
movies.loc[:, "cast"] = movies["cast"].apply(extract_name)

In [18]:
movies.head(1)

,id,overview,genres,keywords,title,vote_average,release_date,cast,crew
0,19995,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,7.2,2009-12-10,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]

In [19]:
li = [movies["cast"], movies["genres"], movies["keywords"], movies["crew"]]
lam = lambda x:[i.replace(" ","") for i in x]
new_li = []
for i in li:
    i = i.apply(lam)
    new_li.append(i)

movies.loc[:, 'tags'] = new_li[0] + new_li[1] + new_li[2] + new_li[3]

In [20]:
movies.head(2)

,id,overview,genres,keywords,title,vote_average,release_date,cast,crew,tags
0,19995,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,7.2,2009-12-10,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],"[SamWorthington, ZoeSaldana, SigourneyWeaver, ..."
1,285,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,6.9,2007-05-19,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski],"[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste..."

In [21]:
movies['tags'].head(2)

0    [SamWorthington, ZoeSaldana, SigourneyWeaver, ...
1    [JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...
Name: tags, dtype: object

In [22]:
def split_overview(x):
    if isinstance(x, str):  # Check if the element is a string
        return x.split()
    else:
        return []

movies.loc[:,"overview"] = movies["overview"].apply(split_overview)

In [23]:
movies.loc[:, "tags"] = movies["overview"] + movies["tags"]

In [24]:
movies['tags'].head(2)

0    [In, the, 22nd, century,, a, paraplegic, Marin...
1    [Captain, Barbossa,, long, believed, to, be, d...
Name: tags, dtype: object

In [25]:
movies.loc[:, 'tags'] = movies['tags'].apply(lambda x: " ".join(x))
movies.loc[:, 'overview'] = movies['overview'].apply(lambda x: " ".join(x))
movies.loc[:, 'genres'] = movies['genres'].apply(lambda x: ", ".join(x))
movies.loc[:, 'keywords'] = movies['keywords'].apply(lambda x: " ".join(x))
movies.loc[:, 'cast'] = movies['cast'].apply(lambda x: ", ".join(x))
movies.loc[:, 'crew'] = movies['crew'].apply(lambda x: ",  ".join(x))

In [26]:
movies['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. SamWorthington ZoeSaldana SigourneyWeaver StephenLang Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d JamesCameron'

In [27]:
movies.loc[:, "tags"] = movies["tags"].apply(lambda x:x.lower())
movies.head(3)

,id,overview,genres,keywords,title,vote_average,release_date,cast,crew,tags
0,19995,"In the 22nd century, a paraplegic Marine is di...","Action, Adventure, Fantasy, Science Fiction",culture clash future space war space colony so...,Avatar,7.2,2009-12-10,"Sam Worthington, Zoe Saldana, Sigourney Weaver...",James Cameron,"in the 22nd century, a paraplegic marine is di..."
1,285,"Captain Barbossa, long believed to be dead, ha...","Adventure, Fantasy, Action",ocean drug abuse exotic island east india trad...,Pirates of the Caribbean: At World's End,6.9,2007-05-19,"Johnny Depp, Orlando Bloom, Keira Knightley, S...",Gore Verbinski,"captain barbossa, long believed to be dead, ha..."
2,206647,A cryptic message from Bond’s past sends him o...,"Action, Adventure, Crime",spy based on novel secret agent sequel mi6 bri...,Spectre,6.3,2015-10-26,"Daniel Craig, Christoph Waltz, Léa Seydoux, Ra...",Sam Mendes,a cryptic message from bond’s past sends him o...

In [28]:
#apply stemming
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

movies.loc[:, "tags"] = movies["tags"].apply(stem)

In [29]:
movies["tags"][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. samworthington zoesaldana sigourneyweav stephenlang action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d jamescameron'

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words="english", max_features=5000)
vectors = vectorizer.fit_transform(movies["tags"]).toarray()

In [31]:
vectors.shape

(4803, 5000)

In [32]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)
similarity.shape

MemoryError: Unable to allocate 183. MiB for an array with shape (4803, 5000) and data type float64

In [33]:
def recommend(movie):
    movie_index = movies[movies['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:11]
    for i in movies_list:
        print(movies.iloc[i[0]].title)

In [34]:
recommend("The Truman Show")

NameError: name 'similarity' is not defined

In [35]:
import joblib

In [37]:
joblib.dump(movies.to_dict(), "movies_data.joblib")

['movies_data.joblib']

In [38]:
joblib.dump(similarity, "similarity.joblib")

['similarity.joblib']

In [39]:
d = joblib.load("Model/movies_data.joblib")

In [40]:
detail = pd.DataFrame(d)

In [41]:
detail.head(1)

,id,overview,genres,keywords,title,vote_average,release_date,cast,crew,tags
0,19995,"In the 22nd century, a paraplegic Marine is di...","Action, Adventure, Fantasy, Science Fiction",culture clash future space war space colony so...,Avatar,7.2,2009-12-10,"Sam Worthington, Zoe Saldana, Sigourney Weaver...",James Cameron,"in the 22nd century, a parapleg marin is dispa..."

In [42]:
li = []
date = detail["release_date"].tolist()

for i in date:
    if i > "2017-01-01":
        li.append(i)
        
li

['2017-02-03', 'N/A']